name: TitancraftQOL
version: '${version}'
main: me.idkdom.titancraftqol.TitancraftQOL
api-version: '1.21'
description: Quality-of-life tweaks for Titancraft

commands:
  titancraftqol:
    description: Reloads TitancraftQOL config
    usage: /titancraftqol reload
    permission: titancraftqol.admin

permissions:
  titancraftqol.admin:
    default: op
