name: TitancraftQOL
version: '${version}'
main: me.idkdom.titancraftqol.TitancraftQOL
api-version: '1.21.1'
description: Quality-of-life tweaks for the Titancraft Minecraft Server

commands:
  titancraftqol:
    description: Main command for titancraftQOL
    usage: /titancraftqol
    permission: titancraftqol.admin

permissions:
  titancraftqol.admin:
    default: op
